### PR TITLE
Support charset detector  for web

### PR DESCRIPTION
**Pull request by dab246**
## Issue

- https://github.com/amake/flutter_charset_detector/issues/3

## Desccriptions

-  Use `https://www.npmjs.com/package/jschardet` to detect charset on web

### CODE REVIEW

**Comment by dab246** [comment]
@amake  Please review help me. Thanks

**Comment by amake** [comment]
Wow, thanks! This is much appreciated. Please give me a bit of time to take a proper look.

**Comment by amake** [comment]
Thank you for your contribution.

I pushed a bunch of fixes for things. I am almost ready to merge, but there are some outstanding issues:

- It seems that you (or someone) have already claimed the package [flutter_charset_detector_web](https://pub.dev/packages/flutter_charset_detector_web). Are you willing to give this to me? If so, I think I will have to do:
   1. Add you as a member of [my publisher](https://pub.dev/publishers/madlon-kay.com/packages)
   2. Have you transfer ownership of the package to my publisher
   3. Probably remove you from the publisher
- The current implementation uses [`js`](https://pub.dev/packages/js) 0.6.7, which is one major version (equivalent) out of date.
  - Can I update it?
  - Apparently `js` is deprecated in favor of `dart:js_interop`; would it be a problem for me to switch to this at some time?

**Comment by dab246** [comment]
> Thank you for your contribution.
> 
> I pushed a bunch of fixes for things. I am almost ready to merge, but there are some outstanding issues:
> 
> * It seems that you (or someone) have already claimed the package [flutter_charset_detector_web](https://pub.dev/packages/flutter_charset_detector_web). Are you willing to give this to me? If so, I think I will have to do:
>   
>   1. Add you as a member of [my publisher](https://pub.dev/publishers/madlon-kay.com/packages)
>   2. Have you transfer ownership of the package to my publisher
>   3. Probably remove you from the publisher
> * The current implementation uses [`js`](https://pub.dev/packages/js) 0.6.7, which is one major version (equivalent) out of date.
>   
>   * Can I update it?
>   * Apparently `js` is deprecated in favor of `dart:js_interop`; would it be a problem for me to switch to this at some time?

That's great, thank you. 

- Yes, I myself published the package [flutter_charset_detector_web](https://pub.dev/packages/flutter_charset_detector_web). I am willing to transfer ownership of that package to your publisher, so please add me as a member of [my publisher](https://pub.dev/publishers/madlon-kay.com/packages)
- IMO, at this point we can still use it.

**Comment by amake** [comment]
Thanks! I've invited you to the publisher via the email address on your GitHub profile.

**Comment by dab246** [comment]
> Thanks! I've invited you to the publisher via the email address on your GitHub profile.

Sorry I use this email `datx1995@gmail.com` for my pub.dev. Please invite me back via this email. Sorry for the inconvenience. Thanks.

**Comment by amake** [comment]
OK I've invited you.

**Comment by dab246** [comment]
> OK I've invited you.

II have successfully transferred [flutter_charset_detector_web](https://pub.dev/packages/flutter_charset_detector_web) to your publisher. Please do further work to merge this PR soon. Thanks a lot.

**Comment by amake** [comment]
OK thanks, I'll take it from here.

**Pull request merged**
